### ISSUE TITLE
CVNBot: not able to reload wikis

### ISSUE THREAD

**Issue by valhallasw** [countervandalism/CVNBot#25]
From https://phabricator.wikimedia.org/T152494#2863019:
> ```
> [13:20]	<mafk> CVNBot8 reload ff.wikipedia
> [13:20]	<CVNBot8> Unable to reload:
> Unable to retrieve https://ff.wikipedia.org/w/api.php?action=query&meta=siteinfo&siprop=namespaces&format=xml from server.
> Error was: Error getting response stream (Write: The authentication or decryption has failed.): SendFailure
> ```
Sorry for reporting here but I don't know where else to do so.

**Comment by rxywm** [comment]
✔️ fixed. same as #20
