### ISSUE TITLE
Can not load webresources due to "SecureChannelFailure#012" occured

### ISSUE THREAD

**Issue by rxywm** [countervandalism/CVNBot#46]
- rxy : CVNBot27 load hr.wikipedia
- CVNBot27 : Unable to add project: Unable to retrieve https://hr.wikipedia.org/w/api.php?format=xml&action=query&meta=siteinfo&siprop=namespaces from server. Error was: Error: SecureChannelFailure (The authentication or decryption has failed.)

Oct 11 17:02:13 cvn-app9 CVNBot.exe[1486]: ERROR [Main] CVNBot.Program [CVNBot27] Add project failed#012System.Exception: Unable to retrieve https://hr.wikipedia.org/w/api.php?format=xml&action=query&meta=siteinfo&siprop=namespaces from server. Error was: Error: SecureChannelFailure (The authentication or decryption has failed.)#012  at CVNBot.CVNBotUtils.GetRawDocument (System.String url) [0x0006c] in <41b7a280f8604822832dac88d2357f10>:0 #012  at CVNBot.Project.GetNamespaces (System.Boolean snamespacesAlreadySet) [0x0002c] in <41b7a280f8604822832dac88d2357f10>:0 #012  at CVNBot.Project.RetrieveWikiDetails () [0x00000] in <41b7a280f8604822832dac88d2357f10>:0 #012  at CVNBot.ProjectList.AddNewProject (System.String projectName, System.String interwiki) [0x0022e] in <41b7a280f8604822832dac88d2357f10>:0 #012  at CVNBot.Program.Irc_OnChannelMessage (System.Object sender, Meebey.SmartIrc4net.IrcEventArgs e) [0x00596] in <41b7a280f8604822832dac88d2357f10>:0

**Comment by rxywm** [comment]
It seems can be avoid this error by using Mono 4.8.0 or later
(tested by docker mono:4.8)

**Comment by Krinkle** [comment]
Fixed by https://github.com/countervandalism/infrastructure/commit/2906b105160e4df45a977d51319b5bb3f729cc17.
